name: Test

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod  # Add this line to reference the "prod" environment
    
    steps:
    - name: Test write permission
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 186.32.90.71
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -eux
          mkdir -p /home/cativo23/deploy/portfolio-api-deploy
          touch /home/cativo23/deploy/portfolio-api-deploy/test.txt
          echo "ok" > /home/cativo23/deploy/portfolio-api-deploy/test.txt